---
cf-domain-name-production: fr.cloud.gov
cf-domain-name-staging: fr-stage.cloud.gov
cf-organization: cloud-gov
cf-space: bots
cf-api-staging: api.fr-stage.cloud.gov
admin-user-staging: sandbox-bot-user